//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restoran.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class kirillov_RestoEntities : DbContext
    {
        public kirillov_RestoEntities()
            : base("name=kirillov_RestoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Cheque> Cheque { get; set; }
        public virtual DbSet<ChequePosition> ChequePosition { get; set; }
        public virtual DbSet<Position> Position { get; set; }
        public virtual DbSet<Table> Table { get; set; }
        public virtual DbSet<Waiter> Waiter { get; set; }
    }
}
